language: c
cache: ccache
git:
  submodules: false
  quiet: true

dist: focal

osx_image: xcode10.2

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

arch:
  - amd64

script:
  - cmake -Bbuild --build .
  - cd build && make pkcs11-daemon pkcs11-proxy

jobs:
  include:
    - stage: GitHub Release
      if: tag =~ ^v
      script: 
        - cmake -Bbuild --build -DCMAKE_BUILD_TYPE=Release .
        - cd build
        - make pkcs11-daemon pkcs11-proxy
        - cpack
      compiler: clang
      os: linux
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: "*.deb"
        prerelease: true
